In [17]:
import numpy as np

In [18]:
nad = np.array([1,2,3,4,5,6,7])
crow = np.array([[1,3,5],[7,2,5],[4,3,5]])
print(nad)
print(crow)

[1 2 3 4 5 6 7]
[[1 3 5]
 [7 2 5]
 [4 3 5]]


In [19]:
nad[2] = 2
print(nad)
nad.ndim

[1 2 2 4 5 6 7]


1

In [20]:
print(arr[8:1:-2])

NameError: name 'arr' is not defined

In [21]:
print(crow[0:3,2:3])

[[5]
 [5]
 [5]]


In [24]:
print(crow[2,-2:])

[3 5]


In [ ]:
print(crow[0:3,1::-1])

In [23]:
arr = np.array([[1,2,3,4],[5,6,8,7],[9,10,11,12]])
print(arr[1:3 ,:0:-1])

[[ 7  8  6]
 [12 11 10]]


In [25]:
void  = arr.copy()
dcop = void.view()
deca = arr[::]

In [26]:
print(arr)
print(void)
print(dcop)
print(deca)

[[ 1  2  3  4]
 [ 5  6  8  7]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  8  7]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  8  7]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  8  7]
 [ 9 10 11 12]]


In [27]:
deca[2,2] =11

In [28]:
void.view()[2,2] = 33

In [15]:
spar = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
flop = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
dgb = np.array([[[[1,2],[3,4]],[[5,6],[7,8]],
    [[9,10],[11,12]]],[[[13,14],[15,16]],[[17,18],[19,20]],[[21,22],[23,24]]]])

mato = spar.reshape(12,1,1)

In [29]:
23, 2spar.ndim
spar.shape
flop.ndim
flop.shape

(2, 3, 2)

In [52]:
dgb.shape
print(dgb)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]]

  [[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]


In [55]:
 You ignored an opportunity to win material.
call = dgb.reshape(12,2)[::-1,::-1]
call

array([[24, 23],
       [22, 21],
       [20, 19],
       [18, 17],
       [16, 15],
       [14, 13],
       [12, 11],
       [10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [100]:
grand = dgb.reshape(1,24)
s = 0
for e in grand[0]:
    s+= e
print(s)

300


In [93]:
drad = np.concatenate((arr,void))
dred = np.stack((arr,void))
drad 

array([[ 1,  2,  3,  4],
       [ 5,  6,  8,  7],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  8,  7],
       [ 9, 10, 33, 12]])

In [99]:
flop = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  8,  7],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  8,  7],
       [ 9, 10, 33, 12]])

In [151]:
import pandas as pd 
data = pd.read_csv('dog_intelligence.csv',header=None)
data = data[1:]
smart_dogs = []
for d in data.values[:-11]:
    if float(d[3][:-1]) > 50:
        smart_dogs.append(d[1:2])
smart_dogs


[array(['Border Collie'], dtype=object),
 array(['Poodle'], dtype=object),
 array(['German Shepherd'], dtype=object),
 array(['Golden Retriever'], dtype=object),
 array(['Doberman Pinscher'], dtype=object),
 array(['Shetland Sheepdog'], dtype=object),
 array(['Labrador Retriever'], dtype=object),
 array(['Papillon'], dtype=object),
 array(['Rottweiler'], dtype=object),
 array(['Australian Cattle Dog'], dtype=object),
 array(['Pembroke Welsh Corgi'], dtype=object),
 array(['Miniature Schnauzer'], dtype=object),
 array(['English Springer Spaniel'], dtype=object),
 array(['Belgian Shepherd Dog (Tervuren)'], dtype=object),
 array(['Schipperke'], dtype=object),
 array(['Belgian Sheepdog'], dtype=object),
 array(['Collie'], dtype=object),
 array(['Keeshond'], dtype=object),
 array(['German Shorthaired Pointer'], dtype=object),
 array(['Flat-Coated Retriever'], dtype=object),
 array(['English Cocker Spaniel'], dtype=object),
 array(['Standard Schnauzer'], dtype=object),
 array(['Brittany'], d

In [137]:
data.values[0]

array(['0', 'Border Collie', 'Brightest Dogs', '95%', '1', '4'],
      dtype=object)